# Generated by Django 3.2.5 on 2021-07-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_remove_images_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='head',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
