# Generated by Django 3.2.5 on 2021-08-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_rental_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='description',
            new_name='house_detail',
        ),
    ]
