# Generated by Django 3.2.5 on 2021-08-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_rename_description_rental_house_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='price',
            field=models.IntegerField(),
        ),
    ]
