# Generated by Django 3.2.5 on 2021-08-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_alter_rental_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='rental',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
